FROM node:boron
MAINTAINER Chris Freeman <cfreeman29@gmail.com>

RUN apt-get update && apt-get clean
RUN npm install -g http
RUN npm install -g request
RUN npm install -g discord.js

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

EXPOSE 9001
